### ISSUE TITLE
One question on F-Score

### ISSUE THREAD

**Issue by yesterday-Luo** [LiyingCV/Long-Range-Grouping-Transformer#12]
When I testing on ShapeNet dataset with F-score, I find it will waste too much time. A little help from you would be greatly appreciated!

**Comment by LiyingCV** [comment]
Hi, we test F-score based on open3d. It will waste time since it needs to sample points.  For the computing details, please refer to [Legoformer](https://github.com/faridyagubbayli/LegoFormer), we use similar methods except for a different open3d version.

**Comment by yesterday-Luo** [comment]
Thanks for your replying! And I have another question about "Evaluation on the Pix3D Dataset". Could you tell me some training details when you train on ShapeNet Chair dataset with random background from SUN database?

**Comment by LiyingCV** [comment]
> Thanks for your replying! And I have another question about "Evaluation on the Pix3D Dataset". Could you tell me some training details when you train on ShapeNet Chair dataset with random background from SUN database?

Hi, the training configuration is similar to the experiments on ShapeNet except we only train a few epochs on ShapeNet Chair dataset.

**Comment by eolgaeng-i** [comment]
I’ve been referencing the Pix2Vox issue as well, but I’m still getting different results. Would it be possible for you to kindly share the full code for calculating the F1-score?

Thank you in advance for your help!

**Comment by LiyingCV** [comment]
> I’ve been referencing the Pix2Vox issue as well, but I’m still getting different results. Would it be possible for you to kindly share the full code for calculating the F1-score?
> 
> Thank you in advance for your help!

Hi, the code we used is the same as [Legoformer](https://github.com/faridyagubbayli/LegoFormer). We have tested the F-score of the pre-trained Pix2Vox++, unfortunately, we also obtained the F-Score which is different from Pix2Vox++ paper. Besides, we also find similar wrong results in the issue [76,](https://github.com/hzxie/Pix2Vox/issues/76#issuecomment-873491943). Thus we recommend directly using the test code of [Legoformer](https://github.com/faridyagubbayli/LegoFormer).

**Comment by eolgaeng-i** [comment]
> Hi, the code we used is the same as [Legoformer](https://github.com/faridyagubbayli/LegoFormer). We have tested the F-score of the pre-trained Pix2Vox++, unfortunately, we also obtained the F-Score which is different from Pix2Vox++ paper. Besides, we also find similar wrong results in the issue [76,](https://github.com/hzxie/Pix2Vox/issues/76#issuecomment-873491943). Thus we recommend directly using the test code of [Legoformer](https://github.com/faridyagubbayli/LegoFormer).

Hi, thank you so much for your prompt and kind response! I really appreciate the clarification and your suggestion to use the Legoformer test code. I will go ahead and follow your advice. Thanks again for your help, and I’m glad to say that the issue is now resolved!

**Comment by Tcode8** [comment]
> 集上进行测试时，我发现这会浪

Hello, I am unable to measure the value in my paper using the F1 score code of LegoFormer. May I ask how you measured it

**Comment by LiyingCV** [comment]
> > 感谢您的回复！我还有一个关于“Pix3D 数据集评估”的问题。您能否告诉我在 ShapeNet Chair 数据集上使用来自 SUN 数据库的随机背景进行训练时的一些训练细节？
> 
> Hello, I am unable to measure the value in my paper using the F1 score code of LegoFormer. May I ask how you measured it

Hi, we will consider releasing the F1 score test code. Maybe it needs some time; it is necessary to clean the test code since we have not used this code for a long time :)

**Comment by Tcode8** [comment]
> > > 感谢您的回复！我还有一个关于“Pix3D 数据集评估”的问题。您能否告诉我在 ShapeNet Chair 数据集上使用来自 SUN 数据库的后台随机进行训练时的一些细节训练？
> > 
> > 
> > 您好，我无法使用 LegoFormer 的 F1 分数代码测量我的论文中的值。请问您是如何测量的
> 
> 嗨，我们会考虑发布 F1 分数测试代码。可能需要一些时间；由于我们很久没有使用此代码了，因此有必要清理测试代码 :)

Thank you very much for your work！
