### ISSUE TITLE
No F-score@1% related code found

### ISSUE THREAD

**Issue by leezanla** [LiyingCV/Long-Range-Grouping-Transformer#17]
Hello, in your code, I did not find that there is F-score@1% evaluation related code. May I ask, how did you achieve the F-score@1% evaluation? The data set I tested was ShapeNet.

**Comment by LiyingCV** [comment]
Hi, please refer to [issues 12](https://github.com/LiyingCV/Long-Range-Grouping-Transformer/issues/12).
