### ISSUE TITLE
help!    how  to rendering vox  as same  angle    ?

### ISSUE THREAD

**Issue by epicgzs1112** [LiyingCV/Long-Range-Grouping-Transformer#2]
![howtorendering](https://github.com/LiyingCV/Long-Range-Grouping-Transformer/assets/73538248/7e21ff16-4a48-4dc8-be1a-1680366ce746)
老铁，怎样像你论文里一样用同一个角度渲染体素啊，我使用了bpy-visualization-utils-master，但是依然无法调整绕Z轴的旋转。

**Comment by LiyingCV** [comment]
Hi, you can reset the camera pose or object position to adjust the rendering image.
