### ISSUE TITLE
release the code !(^-^)! hurry up!

### ISSUE THREAD

**Issue by SWWdz** [LiyingCV/Long-Range-Grouping-Transformer#3]
release the code !(^-^)! hurry up!

**Comment by george-kalitsios** [comment]
release the code !(^-^)! hurry up!

**Comment by LiyingCV** [comment]
Hi, we will release the complete model code in December 2023.

**Comment by LiyingCV** [comment]
The complete model code has been released, so I close this comment.

**Comment by SWWdz** [comment]
Where is the runner.py? I can't find in your project.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiyingCV/Long-Range-Grouping-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月24日(星期天) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiyingCV/Long-Range-Grouping-Transformer] release the code !(^-^)! hurry up! (Issue #3)





 
The complete model code has been released, so I close this comment.

**Comment by george-kalitsios** [comment]
Could you please check the config.py file for errors? Several parameters are missing.

**Comment by LiyingCV** [comment]
> Could you please check the config.py file for errors? Several parameters are missing.

Hi, could you tell me which parameters are missing? The code worked fine before I uploaded it.

**Comment by george-kalitsios** [comment]
__C.NETWORK.ENCODER.VIT.USE_CLS_TOKEN
__C.NETWORK.DECODER.VOXEL_SIZE 
__C.TRAIN.UPDATE_N_VIEWS_RENDERING_PER_EPOCH 
__C.TRAIN.UPDATE_N_VIEWS_RENDERING_PER_ITERATION 
__C.NETWORK.DECODER.GROUP.SOFTMAX_DROPOUT
__C.NETWORK.DECODER.GROUP.ATTENTION_MLP_DROPOUT
__C.NETWORK.MERGER.FC.DIM

**Comment by george-kalitsios** [comment]
I was able to run the code, however keep the following four issues in mind:  1) TypeError: forward() got an unexpected keyword argument 'lga'
2) AttributeError: module 'utils.helpers' has no attribute 'reduce_value'
    self.layer_norm = torch.nn.LayerNorm(cfg.NETWORK.MERGER.FC.DIM)
3) AttributeError: 'EasyDict' object has no attribute 'FC'
4) TypeError: forward() got an unexpected keyword argument 'overlap'

**Comment by LiyingCV** [comment]
> I was able to run the code, however keep the following four issues in mind: 1) TypeError: forward() got an unexpected keyword argument 'lga' 2) AttributeError: module 'utils.helpers' has no attribute 'reduce_value' self.layer_norm = torch.nn.LayerNorm(cfg.NETWORK.MERGER.FC.DIM) 3) AttributeError: 'EasyDict' object has no attribute 'FC' 4) TypeError: forward() got an unexpected keyword argument 'overlap'

Hi, I get it. Maybe due to the wrong version of the uploaded code. I will check them later, and you can download the new version code this weekend.

**Comment by LiyingCV** [comment]
> I was able to run the code, however keep the following four issues in mind: 1) TypeError: forward() got an unexpected keyword argument 'lga' 2) AttributeError: module 'utils.helpers' has no attribute 'reduce_value' self.layer_norm = torch.nn.LayerNorm(cfg.NETWORK.MERGER.FC.DIM) 3) AttributeError: 'EasyDict' object has no attribute 'FC' 4) TypeError: forward() got an unexpected keyword argument 'overlap'

I updated the code, and you can re-download them. If you have any other questions, please contact us.
