### ISSUE TITLE
help! can your offer ShapeNetChairRFC datasets?

### ISSUE THREAD

**Issue by epicgzs1112** [LiyingCV/Long-Range-Grouping-Transformer#5]

**Comment by LiyingCV** [comment]
Hi, sorry that we currently do not plan to release the ShapeNetChairRFC dataset. For generating the dataset, you can follow the generation approach referred to in Pix2Vox++.

**Comment by epicgzs1112** [comment]
could you  describ more detail about  generating the dataset! (@^ @)!

**Comment by LiyingCV** [comment]
> could you describ more detail about generating the dataset! (@^ @)!

Hi, you need to use the [Render tool](https://github.com/ShapeNet/RenderForCNN) to generate 60 images for each chair in the ShapeNet. By the way, you need to add the backgrounds samples from the [SUN database](https://groups.csail.mit.edu/vision/SUN/hierarchy.html).
