### ISSUE TITLE
How to train and test using only one GPU

### ISSUE THREAD

**Issue by Chu-Orion** [LiyingCV/Long-Range-Grouping-Transformer#7]
Great job! But I only have one GPU. What configuration should I modify so that I can conduct training and testing? Thank you

**Comment by LiyingCV** [comment]
Hi, you can set the config in `train.sh`:  `nproc_per_node` to 1 (which means only use one device) and `CUDA_VISIBLE_DEVICES` to any device ID you want to use (e.g., if you want to use the device whose ID is 2, then you set this parameter to 2)

**Comment by Chu-Orion** [comment]
thank you for your help!!!，the model is already being trained!!! have a good day
